site_name: 3D Visual Standards Hub
site_url: https://shawhir.github.io/KnowledgeHub/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    # (omit navigation.sections)
    - toc.integrate   # optional
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
# optional but nice to keep, it's on by default
plugins:
  - search
nav:
  - Home: index.md
  - GLTF Manifesto:
      - Overview: gltf/introduction.md
      - Asset Structure: gltf/asset_structure.md
      - File Format: gltf/file_format.md
      - Coordinate System: gltf/coordinate_system.md
      - Detail Levels: gltf/detail_levels.md
      - Materials and Textures: gltf/materials_and_textures.md
      - Materials and Group Names: gltf/materials_and_group_names.md
      - Animation: gltf/animation.md
      - Texture Files: gltf/texture_files.md
      - Texture Map Examples: gltf/texture_map_examples.md
      - Level of Detail: gltf/level_of_detail.md
      - LOD Standards and Metadata: gltf/lod_standards_and_metadata.md
      - Directory Structure: gltf/directory_structure_example.md
      - Repository Structure: gltf/repository_structure_example.md
      - Bits and Pieces: gltf/bits_and_pieces.md
  - Textures QA:
      - Overview: textures_qa/introduction.md
      - Directory Structure: textures_qa/directory_structure.md
      - File Requirements: textures_qa/file_requirements.md
      - Naming Conventions: textures_qa/naming_conventions.md
      - Texture Sizing: textures_qa/texture_sizing.md
  - Trees & Vegetation:
      - Overview: vegetation/introduction.md
      - Asset structure: vegetation/asset_structure.md
      - File format: vegetation/file_format.md
      - Coordinate system: vegetation/coordinate_system.md
      - Detail levels: vegetation/detail_levels.md
      - Materials and Textures: vegetation/materials_and_textures.md
      - Material and Group names: vegetation/materials_and_group_names.md
      - Animation (Beta): vegetation/animation.md
      - Texture Files: vegetation/texture_files.md
  - Tutorials:
      - Overview: tutorials/index.md
      - Blender Scene Cleanup (Pompeii Example): tutorials/blender_scene_cleanup.md
      - Cities at Night: tutorials/cities_at_night.md